---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php package
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes

  - name: install mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution ==  "Ubuntu"
