---

- hosts: all
  become: true
  tasks:

  - name: start apache2 (Ubuntu)
    tags: apache,apache2,ubuntu
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == "Ubuntu"
