- name: add ssh key for the new user
  authorized_key:
    user: user1
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOb+a9v8rGtt4Bx+q6u0lvm8fzshdtqR3vEjlLCWn/e ansible"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd

